module.exports = {
  SUGGESTIONS: [
    "Add measurable achievements.",
    "Use action verbs.",
    "Customize your resume for each role.",
    "Add keywords from the job description.",
    "Keep formatting clean and consistent.",
    "Focus on results, not duties.",
    "Keep it under 2 pages.",
    "Start with a strong summary statement.",
    "Quantify your impact where possible.",
    "Tailor your skills section to the job.",
    "Avoid using passive language.",
    "Highlight promotions or career growth.",
    "Include relevant certifications and training.",
    "Use bullet points for readability.",
    "Avoid clichés like 'hard-working' or 'team player'.",
    "Include links to your portfolio or GitHub (if applicable).",
    "Ensure there are no grammar or spelling mistakes.",
    "Use consistent tense and formatting.",
    "Avoid including irrelevant jobs or experiences.",
    "Keep the design simple and professional.",
  ],
  RECOMMENDATION: [
    { title: "Frontend Developer", company: "Google" },
    { title: "Backend Developer", company: "Amazon" },
    { title: "Data Analyst", company: "Meta" },
    { title: "DevOps Engineer", company: "Netflix" },
    { title: "Product Manager", company: "Apple" },
  ],
};
